/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi.testmaximum;

public class TestMaximum {

	public static void main(String[] args) {
		System.out.println("Welcome");
	}
}
