/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi.testmaximum;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class TestMaximumtest {
	@Test
	public void TestMaximumIntegerAtFirstPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Integer result = testMaximum.maximum(100, 30, 40);
		assertEquals((Integer) 100, result);
	}

	@Test
	public void TestMaximumIntegerAtSecondPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Integer result = testMaximum.maximum(100, 300, 40);
		assertEquals((Integer) 300, result);
	}
}
