/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi.testmaximum;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class TestMaximumtest {
	@Test
	public void TestMaximumIntegerAtFirstPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Integer result = testMaximum.maximum(100, 30, 40);
		assertEquals((Integer) 100, result);
	}

	@Test
	public void TestMaximumIntegerAtSecondPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Integer result = testMaximum.maximum(100, 300, 40);
		assertEquals((Integer) 300, result);
	}

	@Test
	public void TestMaximumIntegerAtThirdPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Integer result = testMaximum.maximum(100, 300, 400);
		assertEquals((Integer) 400, result);
	}

	@Test
	public void TestMaximumStringAtFirstPosition() {
		TestMaximum testMaximum = new TestMaximum();
		String result = testMaximum.maximum("Working", "Sleep", "Eat");
		assertEquals("Working", result);
	}

	@Test
	public void TestMaximumStringAtSecondPosition() {
		TestMaximum testMaximum = new TestMaximum();
		String result = testMaximum.maximum("Eat", "Working", "Sleep");
		assertEquals("Working", result);
	}

	@Test
	public void TestMaximumStringAtThirdPosition() {
		TestMaximum testMaximum = new TestMaximum();
		String result = testMaximum.maximum("Eat", "Sleep", "Working");
		assertEquals("Working", result);
	}

	@Test
	public void TestMaximumFloatAtFirstPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Float result = testMaximum.maximum(100.87f, 30.45f, 40.533f);
		assertEquals((Float) 100.87f, result);
	}

	@Test
	public void TestMaximumFloatAtSecondPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Float result = testMaximum.maximum(30.45f, 100.87f, 40.533f);
		assertEquals((Float) 100.87f, result);
	}

	@Test
	public void TestMaximumFloatAtThirdPosition() {
		TestMaximum testMaximum = new TestMaximum();
		Float result = testMaximum.maximum(30.45f, 40.533f, 100.87f);
		assertEquals((Float) 100.87f, result);
	}

}
